controllers:
    resource: ../src/Controller/
    type: attribute

admin_voiture_image_delete:
    path: /admin/voiture/{id}/image/{imageId}/delete
    controller: App\Controller\AdminController::deleteImage
    methods: POST